const ADD_TRACK = "ADD_TRACK";
const UPDATE_TRACK = "UPDATE_TRACK";
const DELETE_TRACK = "DELETE_TRACK";
const UPDATE_MATRIX_LENGTH = "UPDATE_MATRIX_LENGTH";
const CLEAR_MATRIX = "CLEAR_MATRIX";
const RANDOM_FILL_MATRIX = "RANDOM_FILL_MATRIX";

export default {
    ADD_TRACK,
    UPDATE_TRACK,
    DELETE_TRACK,
    UPDATE_MATRIX_LENGTH,
    CLEAR_MATRIX,
    RANDOM_FILL_MATRIX
}