const PLAY_SEQUENCE = "PLAY_SEQUENCE";
const STEP_SEQUENCE = "STEP_SEQUENCE";
const STOP_SEQUENCE = "STOP_SEQUENCE";
const RESET_SEQUENCE = "RESET_SEQUENCE";
const CHANGE_STEPS = "CHANGE_STEPS";

export default {
    PLAY_SEQUENCE,
    STEP_SEQUENCE,
    STOP_SEQUENCE,
    RESET_SEQUENCE,
    CHANGE_STEPS
}
